name: workflow reutilizable deploy Azure

on:
  workflow_call:
    inputs:
      deploy_name:
        required: true
        type: string
      azure_region:
        required: false
        type: string
        default: ''
      scopeLevel:
        required: true
        type: string
      environment:
        required: false
        type: string
      resource_group:
        required: false
        type: string
        default:  ''
      bicep_file:
        required: false
        type: string
        default: main.bicep
      parameter_file:
        required: false
        type: string
        default: ''
      
      # bicep_version:
      #   required: false
      #   type: string
      #   default: 0.42.1 
    secrets:
      AZURE_CLIENT_ID_READER:
        required: true      
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_CLIENT_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
   
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Instalacion de Bicep CLI
      #   run:  az bicep install --version ${{ inputs.bicep_version }}

      - name: Bicep lint
        run: az bicep lint --file ${{ inputs.bicep_file }}

  preview:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      id-token: write                
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID_READER }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      
      - name: Bicep Validate
        uses: azure/bicep-deploy@v2
        with:
          type: deploymentStack
          operation: validate
          name: ${{ inputs.deploy_name }}
          #bicep-version: ${{ inputs.bicep_version }}
          location: ${{ inputs.azure_region }}
          scope: ${{ inputs.scopeLevel }}
          resource-group-name: ${{ inputs.resource_group }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          template-file: ${{ inputs.bicep_file }}
          parameters-file: ${{ inputs.parameter_file }}
          action-on-unmanage-resources: delete
          action-on-unmanage-resourcegroups: detach #'delete' 'detach'
          deny-settings-mode: none
        
      - name: Bicep What-if
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: whatIf
          name: ${{ inputs.deploy_name }}
          #bicep-version: ${{ inputs.bicep_version }}
          location: ${{ inputs.azure_region }}
          scope: ${{ inputs.scopeLevel }}
          resource-group-name: ${{ inputs.resource_group }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          template-file: ${{ inputs.bicep_file }}
          parameters-file: ${{ inputs.parameter_file }}

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write                
      contents: read
    needs: preview
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy a Azure
        uses: azure/bicep-deploy@v2
        with:
          type: deploymentStack
          operation: create
          name: ${{ inputs.deploy_name }}
          #bicep-version: ${{ inputs.bicep_version }}
          location: ${{ inputs.azure_region }}
          scope: ${{ inputs.scopeLevel }}
          resource-group-name: ${{ inputs.resource_group }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          template-file: ${{ inputs.bicep_file }}
          parameters-file: ${{ inputs.parameter_file }}
          action-on-unmanage-resources: delete
          action-on-unmanage-resourcegroups: detach #'delete' 'detach'
          deny-settings-mode: none
